"""
Standalone Executable Builder
==============================

Generate standalone executables from Python functions using Nuitka.
Supports Tkinter and PySide6 GUI frameworks.

The typical workflow from org-babel:

    #+begin_src python :results output :session *Python-EE*
    from electrical.executable.builder import build_app

    def my_app():
        import tkinter as tk
        from tkinter import ttk

        root = tk.Tk()
        root.title("Buck Calculator")
        ttk.Label(root, text="Hello!").pack()
        root.mainloop()

    build_app(my_app, name="buck-calc", gui="tkinter", output_dir="~/Desktop/")
    #+end_src

Or use the template system:

    from electrical.executable.builder import tkinter_template, write_and_build

    code = tkinter_template(
        title="Buck Calculator",
        body="print('Hello from EE!')"
    )
    write_and_build(code, name="buck-calc")
"""

import inspect
import os
import tempfile
import textwrap
from pathlib import Path
from typing import Callable, Optional


# ── Nuitka availability check ────────────────────────────────────────────

def _nuitka_available() -> bool:
    """Check if Nuitka is installed."""
    try:
        import nuitka  # noqa: F401
        return True
    except ImportError:
        return False


# ── Source code extraction ───────────────────────────────────────────────

def _extract_function_source(func: Callable) -> str:
    """Extract the full source code of a function with its decorators."""
    source = inspect.getsource(func)
    return textwrap.dedent(source)


def _generate_entry_point(func_source: str, func_name: str, gui: str = "tkinter") -> str:
    """Generate the entry-point script for the executable."""
    lines = [
        "#!/usr/bin/env python3",
        '"""Auto-generated by itanna-electrical executable builder."""',
        "",
        func_source,
        "",
        "if __name__ == '__main__':",
        f"    {func_name}()",
        "",
    ]
    return "\n".join(lines)


# ── Template generators ──────────────────────────────────────────────────

def tkinter_template(
    title: str = "EE App",
    width: int = 400,
    height: int = 300,
    body: str = "pass",
    extra_imports: str = "",
) -> str:
    """Generate a Tkinter-based application source.

    Args:
        title: Window title
        width: Window width in pixels
        height: Window height in pixels
        body: Python code inserted after the UI setup (e.g. label creation, callbacks)
        extra_imports: Additional import statements

    Returns:
        Full Python source code for the application.
    """
    return f"""#!/usr/bin/env python3
\"\"\"{title} — Auto-generated by itanna-electrical.\"\"\"

import tkinter as tk
from tkinter import ttk
{extra_imports}

def main():
    root = tk.Tk()
    root.title("{title}")
    root.geometry("{width}x{height}")

    # ── UI Body ──────────────────────────────────────────────────────
{textwrap.indent(body, "    ")}

    # ── Main Loop ────────────────────────────────────────────────────
    root.mainloop()

if __name__ == "__main__":
    main()
"""


def pyside6_template(
    title: str = "EE App",
    width: int = 400,
    height: int = 300,
    body: str = "pass",
    extra_imports: str = "",
) -> str:
    """Generate a PySide6-based application source.

    Args:
        title: Window title
        width: Window width in pixels
        height: Window height in pixels
        body: Python code inserted after the UI setup
        extra_imports: Additional import statements

    Returns:
        Full Python source code for the application.
    """
    return f"""#!/usr/bin/env python3
\"\"\"{title} — Auto-generated by itanna-electrical.\"\"\"

import sys
from PySide6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout
{extra_imports}

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("{title}")
        self.resize({width}, {height})
        central = QWidget()
        self.setCentralWidget(central)
        layout = QVBoxLayout(central)

        # ── UI Body ──────────────────────────────────────────────
{textwrap.indent(body, "        ")}

def main():
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
"""


# ── Write and build ──────────────────────────────────────────────────────

def write_script(code: str, output_dir: str = "~/.local/bin/", name: str = "ee-app") -> str:
    """Write a Python script to disk.

    Args:
        code: Python source code
        output_dir: Directory to write to
        name: Script name (without .py extension)

    Returns:
        Path to the written file.
    """
    path = Path(output_dir).expanduser().resolve()
    path.mkdir(parents=True, exist_ok=True)
    filepath = path / f"{name}.py"
    filepath.write_text(code)
    os.chmod(filepath, 0o755)
    return str(filepath)


def write_and_build(
    code: str,
    name: str = "ee-app",
    output_dir: str = "~/.local/bin/",
    nuitka_options: Optional[list] = None,
) -> dict:
    """Write a script and compile it with Nuitka into a standalone executable.

    Args:
        code: Full Python source code
        name: App name (used for output binary)
        output_dir: Output directory for the binary
        nuitka_options: Additional Nuitka CLI options

    Returns:
        Dict with 'status', 'binary_path', and optional 'error'.
    """
    if not _nuitka_available():
        return {
            "status": "error",
            "error": "Nuitka is not installed. Run: pip install nuitka",
        }

    # Write the source
    script_path = write_script(code, output_dir=output_dir, name=name)
    script_path_obj = Path(script_path)

    # Build command
    out_dir = Path(output_dir).expanduser() / f"{name}.dist"
    default_opts = [
        "--standalone",
        "--onefile",
        "--enable-plugin=tk-inter",
        f"--output-dir={out_dir.parent}",
        f"--output-filename={name}",
    ]
    if nuitka_options:
        default_opts.extend(nuitka_options)

    # Run Nuitka
    import subprocess
    cmd = ["python3", "-m", "nuitka"] + default_opts + [str(script_path_obj)]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode == 0:
            binary = Path(output_dir).expanduser() / name
            return {
                "status": "success",
                "binary_path": str(binary),
                "stdout": result.stdout,
            }
        else:
            return {
                "status": "error",
                "error": result.stderr,
                "stdout": result.stdout,
            }
    except subprocess.TimeoutExpired:
        return {"status": "error", "error": "Build timed out after 5 minutes."}
    except Exception as e:
        return {"status": "error", "error": str(e)}


def build_app(
    func: Optional[Callable] = None,
    name: str = "ee-app",
    gui: str = "tkinter",
    output_dir: str = "~/.local/bin/",
    template_args: Optional[dict] = None,
    nuitka_options: Optional[list] = None,
) -> dict:
    """Build a standalone executable from a Python function using Nuitka.

    If `func` is provided, extracts its source and wraps it.
    Otherwise, uses template_args to generate a GUI app.

    Args:
        func: Python function to turn into an executable.
              If None, will generate a template app.
        name: Name for the output binary.
        gui: 'tkinter' or 'pyside6'
        output_dir: Where to place the output binary.
        template_args: Dict passed to the template generator.
                       For tkinter: title, width, height, body, extra_imports
        nuitka_options: Additional Nuitka options.

    Returns:
        Dict with 'status', 'binary_path', and optional 'error'.
    """
    if func is not None:
        # Build from an existing function
        source = _extract_function_source(func)
        func_name = func.__name__
        code = _generate_entry_point(source, func_name, gui=gui)
    else:
        # Build from template
        args = template_args or {}
        if gui == "pyside6":
            code = pyside6_template(**args)
        else:
            code = tkinter_template(**args)

    return write_and_build(code, name=name, output_dir=output_dir,
                           nuitka_options=nuitka_options)


def make_app(code: str, name: str = "ee-app", gui: str = "tkinter") -> str:
    """Generate a standalone executable path WITHOUT building.

    Writes the script to a known location and returns its path.
    Use this when you want to inspect or manually run Nuitka.

    Args:
        code: Python source code (or function source)
        name: App name
        gui: 'tkinter' or 'pyside6'

    Returns:
        Path to the written .py file.
    """
    return write_script(code, output_dir="~/.local/bin/", name=name)
